// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.privacy.trackingprotection.fingerprinting.enabled", true);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "bc08b272-501a-4eca-a5d7-3a1f30bb0f82");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1564782739);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1564783231);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1564789601);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1564781873);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1564781753);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1564781993);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1564783471);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1564783351);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 56479);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1564781565);
user_pref("browser.laterrun.bookkeeping.sessionCount", 8);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b5d1836a-da2f-4f53-be64-66931f6d4889}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1564789575417");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1564791349417");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1564789578417");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1564793178417");
user_pref("browser.search.region", "EG");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190718161435");
user_pref("browser.slowStartup.averageTime", 2136);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1564789665);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1564781580249");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "d77a5560bc9546919844c7acab72cd5e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Thu, 01 Aug 2019 14:58:22 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1564782740);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{69d04a21-da7f-41ea-b899-4ca75db50032}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"5.0.2\"}}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"8de5cc0e-5ada-432d-a29c-34c661a0a1e3\",\"fxmonitor@mozilla.org\":\"6f8e3cb3-f343-4080-8b12-ef474d10544b\",\"screenshots@mozilla.org\":\"285c1487-a8bf-4ca1-956d-72a839157fb0\",\"webcompat-reporter@mozilla.org\":\"78462037-a476-49c4-a29b-0977cae309c9\",\"webcompat@mozilla.org\":\"db873650-fe72-4b11-8e7d-09ea78a7c472\",\"default-theme@mozilla.org\":\"ca784fc9-fba5-4f02-9ce9-01f4f1e63c7f\",\"google@search.mozilla.org\":\"23f70137-fe7e-418b-87e1-601ba06c2d86\",\"amazondotcom@search.mozilla.org\":\"b74071f2-92e6-4b46-8245-d13e1b4d2665\",\"bing@search.mozilla.org\":\"9e03f06f-23b1-44d7-bccf-e7753925d8cc\",\"ddg@search.mozilla.org\":\"2069d8c7-7b52-4615-b892-89eaecfd7d62\",\"ebay@search.mozilla.org\":\"f2e0c8cf-9f7c-47a3-a023-3f94ea08d594\",\"twitter@search.mozilla.org\":\"e0d84152-9f10-41dc-8a41-6a162112b72e\",\"wikipedia@search.mozilla.org\":\"9fb4ef47-9e79-4918-ad60-ff41092ab43b\",\"{e58d3966-3d76-4cd9-8552-1582fbc800c1}\":\"c8fc0735-7674-4425-a2ea-ff320013ed77\",\"{d7ce25e4-e6a8-433e-bb29-ec763dcd26bf}\":\"b8474ec1-7e5e-437b-bc37-0c3d59af85ee\"}");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1564782741);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1564790116);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "139d0fd4-8a78-410a-b1e0-757361aa76a9");
user_pref("security.sandbox.plugin.tempDirSuffix", "dde4af2a-19eb-4474-a639-d04caffb1c0c");
user_pref("services.blocklist.pinning.checked", 1564790412);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1564790410142\"");
user_pref("services.settings.last_update_seconds", 1564790567);
user_pref("services.settings.main.cfr-fxa.last_check", 1564790412);
user_pref("services.settings.main.cfr.last_check", 1564790412);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1564790412);
user_pref("services.settings.main.hijack-blocklists.last_check", 1564790412);
user_pref("services.settings.main.language-dictionaries.last_check", 1564790412);
user_pref("services.settings.main.normandy-recipes.last_check", 1564790567);
user_pref("services.settings.main.onboarding.last_check", 1564790412);
user_pref("services.settings.main.sites-classification.last_check", 1564790412);
user_pref("services.settings.main.tippytop.last_check", 1564790412);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1564790412);
user_pref("services.settings.security.onecrl.checked", 1564790412);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1564789664);
user_pref("toolkit.telemetry.cachedClientID", "d5fbab85-5216-4e94-b586-871cefa1888d");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
